<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhrSJk3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhrSJk3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhrSJk3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhrSJk3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhrSJk3\App_KernelDevDebugContainer([
    'container.build_hash' => 'XhrSJk3',
    'container.build_id' => 'dea9e477',
    'container.build_time' => 1585307178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhrSJk3');
